services:
  nexo-app:
    image: ghcr.io/castrogusttavo/nexo:latest
    container_name: nextjs-app
    restart: unless-stopped
    ports:
      - "44385:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_APP_URL: https://elo.stratustelecom.com.br:44385
      BETTER_AUTH_URL: https://elo.stratustelecom.com.br:44385
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@nexo-db-1:5432/${POSTGRES_DB}
      REDIS_URL: redis://nexo-redis-1:6379
      RESEND_API_KEY: ${RESEND_API_KEY}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
    networks:
      - app-network

networks:
  app-network:
    external: true
    name: nexo_default
