export const ERROR_CODES = {
  // Authentication & Authorization (401, 403)
  UNAUTHORIZED: { code: 'UNAUTHORIZED', status: 401 },
  INVALID_TOKEN: { code: 'INVALID_TOKEN', status: 401 },
  TOKEN_EXPIRED: { code: 'TOKEN_EXPIRED', status: 401 },
  INVALID_CREDENTIALS: { code: 'INVALID_CREDENTIALS', status: 401 },
  FORBIDDEN: { code: 'FORBIDDEN', status: 403 },
  INSUFFICIENT_PERMISSIONS: { code: 'INSUFFICIENT_PERMISSIONS', status: 403 },
  PROJECT_FORBIDDEN: { code: 'PROJECT_FORBIDDEN', status: 403 },
  SEAT_LIMIT_REACHED: { code: 'SEAT_LIMIT_REACHED', status: 403 },
  FEATURE_NOT_IN_PLAN: { code: 'FEATURE_NOT_IN_PLAN', status: 403 },
  INVITATION_EMAIL_MISMATCH: { code: 'INVITATION_EMAIL_MISMATCH', status: 403 },
  CAREER_JOB_FORBIDDEN: { code: 'CAREER_JOB_FORBIDDEN', status: 403 },

  // Client Errors (400, 404, 409, 422, 429)
  BAD_REQUEST: { code: 'BAD_REQUEST', status: 400 },
  VALIDATION_ERROR: { code: 'VALIDATION_ERROR', status: 422 },
  RESOURCE_NOT_FOUND: { code: 'RESOURCE_NOT_FOUND', status: 404 },
  CONFLICT: { code: 'CONFLICT', status: 409 },
  USERNAME_CONFLICT: { code: 'USERNAME_CONFLICT', status: 409 },
  RATE_LIMITED: { code: 'RATE_LIMITED', status: 429 },
  PROJECT_NOT_FOUND: { code: 'PROJECT_NOT_FOUND', status: 404 },
  PROJECT_SLUG_CONFLICT: { code: 'PROJECT_SLUG_CONFLICT', status: 409 },
  INVITATION_NOT_FOUND: { code: 'INVITATION_NOT_FOUND', status: 404 },
  INVITATION_NOT_PENDING: { code: 'INVITATION_NOT_PENDING', status: 409 },
  INVITATION_EXPIRED: { code: 'INVITATION_EXPIRED', status: 410 },
  INVITATION_DUPLICATE: { code: 'INVITATION_DUPLICATE', status: 409 },
  INVITATION_ALREADY_MEMBER: { code: 'INVITATION_ALREADY_MEMBER', status: 409 },
  PROJECT_MEMBER_ALREADY_EXISTS: {
    code: 'PROJECT_MEMBER_ALREADY_EXISTS',
    status: 409,
  },
  PROJECT_MEMBER_NOT_FOUND: { code: 'PROJECT_MEMBER_NOT_FOUND', status: 404 },
  PROJECT_MEMBER_NOT_IN_WORKSPACE: {
    code: 'PROJECT_MEMBER_NOT_IN_WORKSPACE',
    status: 409,
  },
  PROJECT_IDENTIFIER_CONFLICT: {
    code: 'PROJECT_IDENTIFIER_CONFLICT',
    status: 409,
  },
  COUPON_INVALID: { code: 'COUPON_INVALID', status: 422 },
  CAREER_JOB_NOT_FOUND: { code: 'CAREER_JOB_NOT_FOUND', status: 404 },
  CAREER_JOB_CLOSED: { code: 'CAREER_JOB_CLOSED', status: 409 },
  CAREER_JOB_SLUG_TAKEN: { code: 'CAREER_JOB_SLUG_TAKEN', status: 409 },
  MEMBER_IMPORT_INVALID_FORMAT: {
    code: 'MEMBER_IMPORT_INVALID_FORMAT',
    status: 422,
  },
  MEMBER_IMPORT_EMPTY: { code: 'MEMBER_IMPORT_EMPTY', status: 422 },
  STATE_NOT_FOUND: { code: 'STATE_NOT_FOUND', status: 404 },
  STATE_FORBIDDEN: { code: 'STATE_FORBIDDEN', status: 403 },
  STATE_LAST_IN_GROUP: { code: 'STATE_LAST_IN_GROUP', status: 409 },
  STATE_IS_DEFAULT: { code: 'STATE_IS_DEFAULT', status: 409 },
  LABEL_NOT_FOUND: { code: 'LABEL_NOT_FOUND', status: 404 },
  LABEL_FORBIDDEN: { code: 'LABEL_FORBIDDEN', status: 403 },
  ESTIMATE_SETTINGS_NOT_FOUND: {
    code: 'ESTIMATE_SETTINGS_NOT_FOUND',
    status: 404,
  },
  ESTIMATE_SETTINGS_FORBIDDEN: {
    code: 'ESTIMATE_SETTINGS_NOT_FOUND',
    status: 403,
  },
  MODULE_NOT_FOUND: { code: 'MODULE_NOT_FOUND', status: 404 },
  MODULE_FORBIDDEN: { code: 'MODULE_FORBIDDEN', status: 403 },
  MODULE_MEMBER_ALREADY_EXISTS: {
    code: 'MODULE_MEMBER_ALREADY_EXISTS',
    status: 405,
  },
  MODULE_MEMBER_NOT_FOUND: { code: 'MODULE_MEMBER_NOT_FOUND', status: 404 },
  CYCLE_NOT_FOUND: { code: 'CYCLE_NOT_FOUND', status: 404 },
  CYCLE_FORBIDDEN: { code: 'CYCLE_FORBIDDEN', status: 403 },
  CYCLE_ALREADY_ACTIVE: { code: 'CYCLE_ALREADY_ACTIVE', status: 409 },
  CYCLE_MEMBER_ALREADY_EXISTS: {
    code: 'CYCLE_MEMBER_ALREADY_EXISTS',
    status: 409,
  },
  CYCLE_MEMBER_NOT_FOUND: { code: 'CYCLE_MEMBER_NOT_FOUND', status: 404 },

  // Server Errors (500)
  INTERNAL_SERVER_ERROR: { code: 'INTERNAL_SERVER_ERROR', status: 500 },
  DATABASE_ERROR: { code: 'DATABASE_ERROR', status: 500 },
  STORAGE_ERROR: { code: 'STORAGE_ERROR', status: 500 },
  PAYMENT_ERROR: { code: 'PAYMENT_ERROR', status: 502 },
  MAIL_ERROR: { code: 'MAIL_ERROR', status: 502 },
} as const

export type ErrorCode = keyof typeof ERROR_CODES
