import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { headers } from 'next/headers'
import './globals.css'
import { Analytics } from '@vercel/analytics/next'
import { SpeedInsights } from '@vercel/speed-insights/next'
import { Suspense } from 'react'
import { Toaster } from '@/components/ui/sonner'
import { TooltipProvider } from '@/components/ui/tooltip'
import { WebVitals } from '@/lib/axiom/client'
import { cn } from '@/lib/utils'

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const nonce = (await headers()).get('x-nonce') ?? undefined

  return (
    <html lang='en' className={cn('dark', inter.variable)}>
      <body className='root antialiased bg-background h-screen' nonce={nonce}>
        <Suspense>
          <TooltipProvider>
            {children}
            <Toaster />
          </TooltipProvider>
        </Suspense>
        <WebVitals />
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  )
}
