name: CD

on:
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: castrogusttavo/nexo

jobs:
  build-and-push:
    name: Build & Push Image
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix=
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            NEXT_PUBLIC_APP_URL=https://nexo.coodee.dev
          secrets: |
            hugeicons_token=${{ secrets.HUGEICONS_TOKEN }}

  deploy:
    name: Deploy to Production
    needs: build-and-push
    runs-on: self-hosted
    environment:
      name: production
      url: https://elo.stratustelecom.com.br:44385
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to server
        run: |
          cp docker-compose.yml /var/www/nexo/docker-compose.yml
          cd /var/www/nexo/
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker compose down
          docker compose pull
          docker compose up -d --remove-orphans
          docker image prune -f
